# Generated by Django 4.2.26 on 2026-01-15 06:26

from django.db import migrations


def create_managers_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    managers_group, created = Group.objects.get_or_create(name='Managers')

    models_to_grant = [
        ('tests', 'test'),  # Тесты
        ('tests', 'question'),  # Вопросы
        ('tests', 'testattempt'),  # Попытки
        ('tests', 'useranswer'),  # Ответы юзеров
        ('users', 'customuser'),  # Пользователи
    ]

    permissions_to_add = []

    for app_label, model_name in models_to_grant:
        try:
            content_type = ContentType.objects.get(app_label=app_label, model=model_name)
            perms = Permission.objects.filter(
                content_type=content_type,
                codename__in=[
                    f'view_{model_name}',
                    f'add_{model_name}',
                    f'change_{model_name}',
                    # f'delete_{model_name}',
                ]
            )
            permissions_to_add.extend(perms)
        except ContentType.DoesNotExist:
            continue

    managers_group.permissions.set(permissions_to_add)
    print(f"\nГруппа Managers успешно обновлена! Выдано прав: {len(permissions_to_add)}")


class Migration(migrations.Migration):
    dependencies = [
        # Эта миграция должна запускаться ПОСЛЕ создания таблиц users и tests
        ('users', '0001_initial'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_managers_group),
    ]
