# Generated by Django 4.2.26 on 2026-01-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('finished', 'Завершен')], default='published', max_length=20),
        ),
    ]
