# Generated by Django 4.2.26 on 2026-01-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_testattempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('closed', 'Закрыт')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('finished', 'Завершен')], default='in_progress', max_length=20),
        ),
    ]
